# Generated by Django 4.2.1 on 2023-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_citizen_number_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='verification_otp_expire_date',
            field=models.DateField(null=True),
        ),
    ]
