# Generated by Django 4.2.1 on 2023-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_governmentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_type', models.CharField(choices=[('F', 'Federal'), ('P', 'Province'), ('L', 'Local')], max_length=3)),
            ],
        ),
    ]
