# Generated by Django 4.2.1 on 2023-05-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_government'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Government',
        ),
    ]
