# Generated by Django 4.2.1 on 2023-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_government_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='f_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='l_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='m_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Middle name'),
        ),
    ]
