# Generated by Django 4.2.1 on 2023-05-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_citizen_f_name_alter_citizen_l_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenuser',
            options={'verbose_name': 'Citizen'},
        ),
        migrations.AlterModelOptions(
            name='governmentuser',
            options={'verbose_name': 'Government'},
        ),
    ]
