# Generated by Django 4.2.1 on 2023-05-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_citizen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government', to='api.governmentuser'),
        ),
    ]
