# Generated by Django 4.2.1 on 2023-05-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_government_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_opened', models.BooleanField()),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('opened_on', models.DateField()),
                ('job_type', models.CharField(choices=[('PART', 'Part-Time'), ('FULL', 'Full-Time'), ('CONTRACT', 'Contract'), ('TEMPO', 'Temporary'), ('INTERN', 'Internship')], max_length=15)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.government')),
            ],
        ),
    ]
