# Generated by Django 4.2.1 on 2023-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='opened_on',
            field=models.DateField(default=True),
        ),
    ]
