# Generated by Django 4.2.1 on 2023-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_vacancy_opened_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='opened_on',
            field=models.DateField(),
        ),
    ]
