# Generated by Django 4.2.1 on 2023-05-18 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vacancy_is_opened_alter_vacancy_opened_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='opened_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
