# Generated by Django 4.2.1 on 2023-05-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='opened_by',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opened_by', to='api.government'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_vacancy', to='api.vacancy'),
        ),
    ]
