# Generated by Django 4.2.1 on 2023-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
