# Generated by Django 4.2.1 on 2023-05-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_jobapplication_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applied_vacancy', to='api.vacancy'),
            preserve_default=False,
        ),
    ]
