# Generated by Django 4.2.1 on 2023-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv_url',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.ImageField(default='', upload_to='D:\\Programming\\Projects\\hamrorojgar\\backend\\static\\upload'),
        ),
    ]
