# Generated by Django 4.2.1 on 2023-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_jobapplication_cv_url_jobapplication_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.ImageField(upload_to='D:\\Programming\\Projects\\hamrorojgar\\backend\\static\\upload'),
        ),
    ]
