# Generated by Django 4.2.1 on 2023-05-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='p_address_district',
            field=models.CharField(default='', max_length=200, verbose_name='Permanent Address: District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='p_address_municipality',
            field=models.CharField(default='', max_length=200, verbose_name='Permanent Address: Municipality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='p_address_ward_no',
            field=models.IntegerField(default=0, verbose_name='Permanent Address: Ward No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='t_address_district',
            field=models.CharField(max_length=200, null=True, verbose_name='Temporary Address: District'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='t_address_municipality',
            field=models.CharField(max_length=200, null=True, verbose_name='Temporary Address: Municipality'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='t_address_ward_no',
            field=models.IntegerField(null=True, verbose_name='Temporary Address: Ward No.'),
        ),
    ]
