# Generated by Django 4.2.1 on 2023-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_citizen_p_address_citizen_t_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='citizen',
            name='photo',
            field=models.ImageField(null=True, upload_to='D:\\Programming\\Projects\\hamrorojgar\\backend\\static\\upload\\citizen'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.ImageField(upload_to='D:\\Programming\\Projects\\hamrorojgar\\backend\\static\\upload\\job_application'),
        ),
    ]
