# Generated by Django 4.2.1 on 2023-05-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_citizen_photo_url_citizen_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='opened_on',
            new_name='opened_at',
        ),
    ]
