# Generated by Django 4.2.1 on 2023-05-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_opened_on_vacancy_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='location',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='government', to='api.address'),
            preserve_default=False,
        ),
    ]
