# Generated by Django 4.2.1 on 2023-05-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_government_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='photo',
            field=models.ImageField(default='/static/upload/citizen/appIcon.png', upload_to='D:\\Programming\\Projects\\hamrorojgar\\backend\\static\\upload\\citizen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='api.vacancy'),
        ),
    ]
