# Generated by Django 4.2.1 on 2023-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_citizen_photo_alter_qualification_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
