# Generated by Django 4.2.1 on 2023-06-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_jobapplication_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('from_acc', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Pending'), ('PENDING', 'Pending'), ('REFUSED', 'Refused'), ('EXPIRED', 'Expired')], max_length=10)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.citizen')),
                ('for_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.jobapplication')),
                ('payment_using', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.paymentgateway')),
            ],
        ),
    ]
