# Generated by Django 4.2.1 on 2023-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_payment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('REFUSED', 'Refused'), ('EXPIRED', 'Expired')], max_length=10),
        ),
    ]
