# Generated by Django 4.2.1 on 2023-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='payment_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('REFUSED', 'Refused'), ('EXPIRED', 'Expired')], default='Completed', max_length=10),
            preserve_default=False,
        ),
    ]
