# Generated by Django 4.2.1 on 2023-06-09 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_payment_by_alter_payment_for_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='by',
        ),
        migrations.AddField(
            model_name='payment',
            name='by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
