# Generated by Django 4.2.1 on 2023-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_district_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_location_desc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
