# Generated by Django 4.2.1 on 2023-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_citizen_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='number_verification_otp',
            field=models.IntegerField(default=0),
        ),
    ]
