### Reigster Citizen
POST http://127.0.0.1:8000/api/citizen/register
Content-Type: multipart/form-data; boundary=boundary_value

--boundary_value
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
        "user": {
            "email": "rrr@gmail.com",
            "password": "rrr@123",
            "c_password": "rrr@123"
        },
        "f_name": "rise",
        "m_name": "rore",
        "l_name": "revolte",
        "mobile": 12343212,
        "date_of_birth": "2023-05-17",
        "gender": "M",
        "nationality": "nepali",
        "citizenship_no": "453211234432",
        "p_address":{
            "district":"jhapa",
            "municipality":"kamal",
            "ward_no":3
        },
        "t_address":null
}

--boundary_value
Content-Disposition: form-data; name="photo"; filename="appIcon.png"
Content-Type: image/png

< ./assets/images/appIcon.png

--boundary_value--


### Send Verification otp
GET http://127.0.0.1:8000/api/citizen/verify/send-otp/7ab99bc1a312937e04adf94a657d5cbec10ab362d8a9d309d94fccebd7638e78

### Resend Verification otp
GET http://127.0.0.1:8000/api/citizen/verify/resend-otp/7ab99bc1a312937e04adf94a657d5cbec10ab362d8a9d309d94fccebd7638e78

### Login Citizen
POST http://127.0.0.1:8000/api/citizen/login
Content-Type: application/json

{
    "email": "rrrr@gmail.com",
    "password": "rrrr@123"
}

### Logout Citizen
GET http://127.0.0.1:8000/api/citizen/logout
Authorization: Token 4e72012e50fe301aa0170fa9c7e741622729a3e2



### Get Citizen Data
GET http://127.0.0.1:8000/api/citizen
Content-Type: application/json
Authorization: Token 4e72012e50fe301aa0170fa9c7e741622729a3e2


### Get Jobs
GET http://127.0.0.1:8000/api/job

### Get Job
GET http://127.0.0.1:8000/api/job?id=1

### Apply for opened vacancy
POST http://127.0.0.1:8000/api/job/apply?vacancy_id=2
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Token 4e72012e50fe301aa0170fa9c7e741622729a3e2 

--boundary_value
Content-Disposition: form-data; name="json"
Content-Type: application/json;

{
    "description":"hello world"
}

--boundary_value
Content-Disposition: form-data; name="cv"; filename="cv_example.jpg"
Content-Type: image/jpeg

< ./assets/images/cv_example.jpg

--boundary_value--

### Payment
GET http://127.0.0.1:8000/api/payment/khalti?job_application_id=70
Content-Type: application/json
Authorization: Token 4e72012e50fe301aa0170fa9c7e741622729a3e2

# GET http://127.0.0.1:8000/api/jobs/search?q=chat%20service&district=fdsa&municipality=fds

### Search Jobs
GET http://127.0.0.1:8000/api/jobs/search?q=&district=Jhapa&municipality=Kamal

### Get Districts
GET http://127.0.0.1:8000/api/district

### Get Municipalities
GET http://127.0.0.1:8000/api/municipality/5
