### Reigster Citizen
POST http://127.0.0.1:8000/api/citizens/register
Content-Type: multipart/form-data; boundary=boundary_value

--boundary_value
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
        "user": {
            "email": "rr@gmail.com",
            "password": "rrr@123"
        },
        "f_name": "rise",
        "m_name": "rore",
        "l_name": "revolte",
        "mobile": 12343212,
        "date_of_birth": "2023-05-17",
        "gender": "M",
        "nationality": "nepali",
        "citizenship_no": "453211234432",
        "photo_url": "https://stackoverflow.com/questions",
        "p_address":{
            "district":"jhapa",
            "municipality":"kamal",
            "ward_no":3
        },
        "t_address":null
}

--boundary_value
Content-Disposition: form-data; name="photo"; filename="appIcon.png"
Content-Type: image/png

< ./assets/images/appIcon.png

--boundary_value--

### Login Citizen

POST http://127.0.0.1:8000/api/citizens/login
Content-Type: application/json

{
    "email": "rr@gmail.com",
    "password": "rrr@123"
}

### Get Vacancies
GET http://127.0.0.1:8000/api/vacancy

### Apply for opened vacancy
POST http://127.0.0.1:8000/api/job-application?vacancy_id=2
Content-Type: multipart/form-data; boundary=boundary_value
Authorization: Token 14028032abe82899318d080a899a7d82dc9a06a0

# --boundary_value
# Content-Disposition: form-data; name="data"
# Content-Type: application/json

# {
#     "vacancy": 2
# }

--boundary_value
Content-Disposition: form-data; name="cv"; filename="cv_example.jpg"
Content-Type: image/jpeg

< ./assets/images/cv_example.jpg

--boundary_value--