# Generated by Django 4.2.1 on 2023-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, verbose_name='First name')),
                ('m_name', models.CharField(max_length=30, null=True, verbose_name='Middle name')),
                ('l_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('mobile', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=3)),
                ('citizenship_no', models.CharField(max_length=200)),
            ],
        ),
    ]
